version: '3.8'
services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: beafowl
      POSTGRES_PASSWORD: beafowl
      POSTGRES_DB: beafowl
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    restart: always
    build:
        context: ./back
        dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://beafowl:beafowl@postgres:5432/beafowl
    volumes:
      - ./back:/app
      - /app/node_modules

  frontend:
    restart: always
    build:
        context: ./front
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
