name: "Feature request"
description: "Issue for new feature request"
title: "[REQUEST] - Title"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: todo
    attributes:
      label: "To Do"
      description: "What needed to be done"
      value: |
        [TODO]
        Explain what you want to do.
        
        [FORWHAT]
        Explain why you are proposing this feature.

        [REQUIREMENTS]
        Explain what you need for the feature.
    validations:
      required: true
  - type: dropdown
    id: techno
    attributes:
      label: "Techno"
      description: "Technology that will implement the feature"
      multiple: true
      options:
        - Python
        - Java
        - JavaScript
        - C#
        - PHP
        - Swift
        - Kotlin
        - Ruby
        - Rust
        - TypeScript
        - HTML / CSS
        - Not mentioned
