on:
  push:
    branches:
      - main
      - dev
      - AR-78-bug-avec-les-github-actions-du-deploiement-sur-serveur

name: 🚀 Deploy Server on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using ssh key
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/AR-78-bug-avec-les-github-actions-du-deploiement-sur-serveur'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: root
          password: ${{ secrets.FTP_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/BRAVMM/A-Rien.git
            cd A-Rien
            git switch main
            git pull origin main
            cp -r ./* /home/beafowl/A-Rien
            cp /root/.env /home/beafowl/A-Rien/back
            cp /root/.env.development /home/beafowl/A-Rien/front
            sh /home/beafowl/re.sh &

      - name: executing remote ssh commands using ssh key
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/AR-78-bug-avec-les-github-actions-du-deploiement-sur-serveur'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: root
          password: ${{ secrets.FTP_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 2121
          script: |
            git clone https://github.com/BRAVMM/A-Rien.git
            cd A-Rien
            git switch dev
            git pull origin dev
            cp -r ./* /home/beafowl/A-Rien
            cp /root/.env /home/beafowl/A-Rien/back
            cp /root/.env.development /home/beafowl/A-Rien/front
            sh /home/beafowl/re.sh &
