on:
  push:
    branches:
      - main
      - dev

name: 🚀 Deploy Server on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: executing remote ssh commands using ssh key
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: root
          password: ${{ secrets.FTP_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone https://github.com/BRAVMM/A-Rien.git
            cd A-Rien
            git switch main
            git pull origin main
            cp -r ./* /home/beafowl/A-Rien
            cd /home/beafowl/A-Rien/back
            npx dotenv-vault login ${{ secrets.DOTENV_ME_BACK }}
            npx dotenv-vault pull production
            mv .env.production .env
            cd /home/beafowl/A-Rien/front
            npx dotenv-vault login ${{ secrets.DOTENV_ME_FRONT }}
            npx dotenv-vault pull production
            mv .env.production .env
            cd /home/beafowl/A-Rien/mobile
            npx dotenv-vault login ${{ secrets.DOTENV_ME_MOBILE }}
            npx dotenv-vault pull production
            mv .env.production .env
            sh /home/beafowl/re.sh &

      - name: executing remote ssh commands using ssh key
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: root
          password: ${{ secrets.FTP_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: 2121
          script: |
            git clone https://github.com/BRAVMM/A-Rien.git
            cd A-Rien
            git switch dev
            git pull origin dev
            cp -r ./* /home/beafowl/A-Rien
            cd /home/beafowl/A-Rien/back
            npx dotenv-vault login ${{ secrets.DOTENV_ME_BACK }}
            npx dotenv-vault pull production
            mv .env.production .env
            cd /home/beafowl/A-Rien/front
            npx dotenv-vault login ${{ secrets.DOTENV_ME_FRONT }}
            npx dotenv-vault pull production
            mv .env.production .env
            cd /home/beafowl/A-Rien/mobile
            npx dotenv-vault login ${{ secrets.DOTENV_ME_MOBILE }}
            npx dotenv-vault pull production
            mv .env.production .env
            sh /home/beafowl/re.sh &
